name: crojob workflow head
on:
  schedule:
    - cron: '0 2 1 1 *'  # Runs At 02:00 on January 1st every year

jobs:
  cronjob-workflow:
    runs-on: ubuntu-latest
    
    steps:
      - name: cronjob step
        run: echo 'This is a Year cronjob workflow.'
