name: crojob workflow head

on:
  schedule:
    - cron: '0 2 1 * *'  # Runs at 02:00 AM UTC on the 1st of every month

jobs:
  cronjob-workflow:
    runs-on: ubuntu-latest
    
    steps:
      - name: cronjob step
        run: echo 'This is a monthly cronjob workflow.'
