name: value-pass workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter your name"
        required: true
        default: "Gowtam kumar"

jobs:
  get-value-workflow-job:
    runs-on: ubuntu-latest
    outputs:
      message: ${{steps.generate-message.outputs.message}}
    steps:
      - name: Generate Greeting
        id: generate-message
        run: |
          echo "message=helloboss, ${{github.event.inputs.name}}" >> $GITHUB_OUTPUT

  print-value-workflow-job:
    runs-on: ubuntu-latest
    needs: [get-value-workflow-job]

    steps:
      - name: Print Greetings message
        run: |
          echo "${{needs.get-value-workflow-job.outputs.message}}"
